### ISSUE TITLE
Model and setup the scale

### ISSUE THREAD

**Issue by KdiSra** [SmartDogHouse/SmartDogHouse-Software#44]
- [x] Setup hardware
- [x] Model the software
- [x] Tests for the software
- [x] Stubs for running locally the tests

**Comment by igor-lirussi** [comment]
![photo1624618942 (1)](https://user-images.githubusercontent.com/69794393/123417393-020c6e80-d5b8-11eb-9e60-2cd3194babc4.jpeg)
