### ISSUE TITLE
Model and setup the water sensor

### ISSUE THREAD

**Issue by KdiSra** [SmartDogHouse/SmartDogHouse-Software#48]
- [x] Setup hardware
- [x] Model the software
- [x] Tests for the software
- [x] Stubs for running locally the tests

**Comment by igor-lirussi** [comment]
![photo1624618942](https://user-images.githubusercontent.com/69794393/123417025-93c7ac00-d5b7-11eb-9d85-539ed1c77b56.jpeg)
